### ISSUE TITLE
CKFinder integration for php

### ISSUE THREAD

**Issue by maxosp** [ckeditor/ckeditor4-vue#105]
Hi! I ran into the problem of embedding a CKFinder in ckeditor4-vue. I can't find a single example of how to do this specifically for Vue. I use a static archive sceditor and SCFinder on a hosting.

In ckeditor config I have this:

`filebrowserBrowseUrl: 'https://storage.yandexcloud.net/lo-storage-main/frontend-static/ckeditor/ckfinder/ckfinder.html',`

But when I click on 'choose on server' I have this result.

![image](https://user-images.githubusercontent.com/37467552/120344341-2b601480-c302-11eb-8124-c56ae340eab4.png)

Please, explain me what am I did wrong. I can`t find any solutions or explanations hot to do that.

**Comment by sculpt0r** [comment]
Hi @maxosp 

For issues related to CKFinder, please contact [our support](https://ckeditor.com/contact/).

I'm closing this issue since it is not related to a bug in ckeditor4-vue integration. However, if you fix your issue with CKFinder and it comes up that our vue integration should be improved - feel free to report another issue.
