### ISSUE TITLE
Can I use CKEditor without CDN?

### ISSUE THREAD

**Issue by kyuwan** [ckeditor/ckeditor4-vue#133]
I want to use CKEditor even in an environment where I cannot access the CKEditor CDN site.

## Provide detailed reproduction steps (if any)

In an environment with internet, loading from CDN works well.
However, it does not loaded in an environment without internet.
So it still does not work even if you add script.

1. I installed ckeditor4 using npm install ckeditor4. 

2. And I added on my code 
<script src="../../node_modules/ckeditor4/ckeditor.js"></script>

3. but the script is not loaded when I access the page. I think it doesn't work on VueJS

is there any way using CKEditor without CDN? 

### Expected result

CKEditor should be loaded.

### Actual result

CKEditor not loaded.

## Other details

* Browser: Chrome
* OS: Window
* Integration version: ckeditor4-integrations-common@^1.0.0
* CKEditor version: 4.17.1
* Installed CKEditor plugins: contextmenu, dialog, table, justify, font, colorbutton, colordialog, tabletools, tableresize, tableselection

**Comment by sculpt0r** [comment]
Hi @kyuwan 

It is possible to use a specific URL for your ckeditor4, take a look at https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#editor-url. Make sure that if you use relative paths - they are valid and handled correctly by the backend.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
