### ISSUE TITLE
how can i build multiple editors on a page with ckeditor-vue

### ISSUE THREAD

**Issue by elaineKuo** [ckeditor/ckeditor4-vue#142]
## Are you reporting a feature request or a bug?

If there are multiple editors on the same page, only the last editor can trigger the bound event to take effect. The previous editor cannot trigger the bound event. Therefore, adding the key value is useless.

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by sculpt0r** [comment]
Hi @elaineKuo 

I paste the content from your report in the main CKE4 repo - since this one here was empty.

Could you explain: what is the `bound` event? What do you mean by adding the 'key'?

I'm suspecting you are talking about model binding: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#v-model and the 'key` attribute: https://vuejs.org/api/built-in-special-attributes.html#key - but I'm not sure.

Intentions are not clear enough for me. Could you explain more what is your situation by filling correctly the bug report template?
