### ISSUE TITLE
reset css

### ISSUE THREAD

**Issue by 279zlj** [ckeditor/ckeditor4-vue#146]
ckeditor4-vue how to reset ediotor.css and dialog.css

**Comment by sculpt0r** [comment]
Hi @279zlj ,

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
