### ISSUE TITLE
Support Document Editor

### ISSUE THREAD

**Issue by linhongyi** [ckeditor/ckeditor4-vue#147]
As for the title,  I want to know if ckeditor4-vue supports [document editor.](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_example_setups.html#document-editor) 

I didn't find it in the sample, but article editor and inline editor.

thanks.

**Comment by KarolDawidziuk** [comment]
Hi @linhongyi 

Document editor, it's a full version of the editor with additional styles and configuration. 
You can configure it based on [existing sample](https://github.com/ckeditor/ckeditor4-docs-samples/tree/master/editors/document-editor).

In addition, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
