### ISSUE TITLE
How to add custom plugin?

### ISSUE THREAD

**Issue by adyssonferreira** [ckeditor/ckeditor4-vue#17]
I would want to use custom plugin

**Comment by f1ames** [comment]
Please refer to [configuring editor in our Vue docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#config) and [installing plugins guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_plugins.html). 

Also please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on \[Stack Overflow\](https://stackoverflow.com/questions/tagged/ckeditor) next time where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.  
  
If you have CKEditor license, please contact our support team. You also can ask your implementation questions at \[ Stack Overflow\](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by motchju** [comment]
Hi,

I have the same issue, using ckeditor4-vue but can't find how to use CKEditor.plugins.add

**Comment by Johnhong9527** [comment]
CKEditor.plugins.add?

**Comment by jacekbogdanski** [comment]
@motchju @Johnhong9527 additional editor plugins should be added via [Vue configuration](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#config) option and [config.plugins](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-plugins) or [config.extraPlugins](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins) editor options.

Everything has been explained in our documentation, already linked by @f1ames in https://github.com/ckeditor/ckeditor4-vue/issues/17#issuecomment-589531338

Please, read the docs to find out how to resolve this issue.

**Comment by Johnhong9527** [comment]
Thank you, I have solved this problem. It's because I didn't read the code carefully that it would not be used.

**Comment by JsCoderXiaohui** [comment]
> Thank you, I have solved this problem. It's because I didn't read the code carefully that it would not be used.

hello,how do you resolve this issue,could you please share me, I have been confuse in it so long!

**Comment by RobHawk90** [comment]
> > Thank you, I have solved this problem. It's because I didn't read the code carefully that it would not be used.
> 
> hello,how do you resolve this issue,could you please share me, I have been confuse in it so long!

You can use the component [namespaceloaded](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#component-events) event in order to get the instance of CKEDITOR plugin (not the CKEditor middleware), then you are able to do what you want.
Theres more than way to add plugins, so check the docs.

**Comment by pmuhammedov** [comment]
> @motchju @Johnhong9527 additional editor plugins should be added via [Vue configuration](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#config) option and [config.plugins](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-plugins)/[config.extraPlugins](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins).
> 
> Everything has been explained in our documentation, already linked by @f1ames in [#17 (comment)](https://github.com/ckeditor/ckeditor4-vue/issues/17#issuecomment-589531338)
> 
> Please, read the docs to find out how to resolve this issue.

Thank you very much. this helped me and absolutely solved my problem.

**Comment by kalio753** [comment]
> Hi,
> 
> I have the same issue, using ckeditor4-vue but can't find how to use/access CKEditor.plugins.add

After finding on the Vue integration document, I still cannot find the way to put the config for CKEditor.plugins.add somewhere in my code :(

**Comment by huhuang03** [comment]
How can I specify the custom plugin's icon, because the vue project is build for a single file(may be). If I specify the icon by 
```
  window.CKEDITOR.plugins.add('timestamp', {

    // Register the icons. They must match command names.
    icons: 'timestamp',

```

It should not able to find the icons.
