### ISSUE TITLE
How to use custom local skin ?

### ISSUE THREAD

**Issue by rygilles** [ckeditor/ckeditor4-vue#36]
Editor config "skin" is related to CDN, how can I use my local skin folder instead ?

Example: 

```
<template>
    <div>
        <ckeditor v-model="content" :config="editorConfig"></ckeditor>
    </div>
</template>

<script>
    export default {
	props: {
            originalContent: String,
        },
		
        data() {
            return {
		'content': this.originalContent,
                editorConfig: {
                    skin: 'ems'
                },
            }
        }
    }
</script>
```

result trying to load those files:

```
https://cdn.ckeditor.com/4.14.0/standard-all/skins/ems/skin.js
https://cdn.ckeditor.com/4.14.0/standard-all/skins/ems/editor.css
```

**Comment by f1ames** [comment]
Hello @rygilles,
you should be able to use your local skin by additionally adding skin path in `config.skin` option [as mentioned in the docs](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-skin):

```js
config.skin = 'myskin,/customstuff/myskin/';
```

You may also check [Installing skins manually](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_skins.html#installing-skins-manually) guide and [this SO thread](https://stackoverflow.com/questions/29189984/how-can-i-use-the-cdn-version-of-ckeditor-with-an-alternative-skin-hosted-on-my).

---

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) next time where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by rygilles** [comment]
Thank you very much and sorry. I thought "config" was specific to the Vue version.
