### ISSUE TITLE
Event binding lost after undo command

### ISSUE THREAD

**Issue by Dreamer-Somebody** [ckeditor/ckeditor4-vue#40]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. insert my own Html to editor by using setData.
2. binding events on html（In my situation is Vue instantiation）.
3. do something else...
4. execute undo command.

### Expected result

event binding is effective.

### Actual result

Event binding lost

## Other details
I think the bug is related to the implement of undo，html is saved to the undo images，but not the events（ Vue instantiation）. Is there any solution to solve this problem ?

* Browser: Google Chrome 80
* OS: win10
* CKEditor version: 4
* Installed CKEditor plugins: none

**Comment by Dumluregn** [comment]
I transferred an issue instead. It still requires investigation.

**Comment by jswiderski** [comment]
@Dreamer-Somebody  could we ask you to send us a working code so that we could run that sample locally on our servers and see if there are any mistakes in your code or this is indeed a bug in CKEditor? 

With online sample we just see the result, however, we would like to also see the code behind that result.

**Comment by Dreamer-Somebody** [comment]
Here is the source code :  https://github.com/Dreamer-Somebody/ckeditor-demo

**Comment by jacekbogdanski** [comment]
@Dreamer-Somebody the issue is not related to the editor nor integration, but your app implementation. Every time on undo/redo editor replaces its HTML with the one in undo manager stack. It means that all element references are removed and Vue no longer is able to connect a component with HTML.

Basically the purpose of the Vue integration is that the editor can be used as a Vue component, but its content is still managed by editor itself - which means it shouldn't be referenced by Vue directly. If you would like to use the same code you already wrote, you should reinitialize your ColorComp component on editor HTML after every undo/redo events. You can do it e.g. using [afterCommandExec](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-afterCommandExec) for these events.

However, it's safer to just write your own CKEditor 4 widget for this feature, because changing HTML which is referenced by Vue may produce some unexpected results (like memory leaks). You can read more about creating your own widget here: https://ckeditor.com/docs/ckeditor4/latest/guide/widget_sdk_tutorial_1.html

In the end, please, note that our issue tracker is for reporting bugs and new features, but your issue is neither of them. Please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
