### ISSUE TITLE
Accessing the editor instance

### ISSUE THREAD

**Issue by AndrewCloss** [ckeditor/ckeditor4-vue#46]
Hello,

I need to use an on paste event, however the closest thing is an on "input" event. In [this section](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#editor-instance) of the doc it says:

>if you need access to the editor object, you can use the editor property of the component’s instance:
>
>component.instance.getData();

I cant understand how that maps to my current template, because:
 1. `console.log(this.$refs.editor)` is defined
 2. `console.log(this.$refs.editor.instance)` is undefined 
 3. `console.log(this.$refs.editor.on())` is not a function

My vue file:
```
<template>
    <div class="container">
        <ckeditor :editor-url="editorUrl" v-model="editorData" :config="editorConfig"></ckeditor>
    </div>
</template>
```

**Comment by f1ames** [comment]
@AndrewCloss you can [use custom config](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#config) with paste event [added via `on` property](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-on) if you don't have access to `component.instance`.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave similar requests on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) next time where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
