### ISSUE TITLE
how to add the link of the html5 audio? 

### ISSUE THREAD

**Issue by Izzatullo** [ckeditor/ckeditor4-vue#48]
I have faced with the problem of integration of audio into the ckeditor. Tried to use the [https://ckeditor.com/cke4/addon/html5audio](html5audio) but I am getting an error namely **html5audio was not found in ....**. How can I implement it?

**Comment by jacekbogdanski** [comment]
The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
