### ISSUE TITLE
Destroy

### ISSUE THREAD

**Issue by adrianoGaspar** [ckeditor/ckeditor4-vue#53]
How cani destroy Ckeditor 4 on vue js?

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Hi @adrianoGaspar,

CKEditor 4 instance is destroyed together with component instance, see https://github.com/ckeditor/ckeditor4-vue/blob/fa5a23b6a7d0cd360a313ce68496b2a022ec127d/src/ckeditor.js#L91-L97.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question next time on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
