### ISSUE TITLE
this ckeditor support  plugins addExternal?

### ISSUE THREAD

**Issue by huangyangyang-yangyang** [ckeditor/ckeditor4-vue#54]
hello,I'd like to ask you questions,if i'd like addExternal function,for example,add the mathematical formula,What should I do? beacuse, I find official document and this example default is none mathematical formula,mathematical formula  is need a addExternal,thank you!

**Comment by f1ames** [comment]
Hi @huangyangyang-yangyang,

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
