### ISSUE TITLE
I want to get Editor Instance

### ISSUE THREAD

**Issue by sontt-1215** [ckeditor/ckeditor4-vue#76]
Hi Everybody !!!
In the Vue CKEditor doc it says:
```
    if you need access to the editor object, you can use the editor property of the component’s instance:

    component.instance.getData();
```
I cant understand how that maps to my current template, because:
```
    console.log(this.$refs.editor) is defined
    console.log(this.$refs.editor.instance) is undefined
    console.log(this.$refs.editor.on()) is not a function
```
My vue file
```
  <ckeditor
      v-model="form_single_question.content.detail"
      :config="editorConfig"
      @input="autocompleteKatexes('tags_content', 'content')"
      class="w-100"
      id="tags_content"
      ref="editor"
  >
  </ckeditor>
```
Becasue i want to get `selectionStart` (current cursor).
Please help me !!!

**Comment by f1ames** [comment]
Hi @sontt-1215, please keep in mind that:

> Please note that this property is initialised asynchronously, after mounting the component.

So this depends where you have placed `console.log` in the code. You may also find [`namespaceloaded` event](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#namespaceloaded) and [`CKEDITOR.instances.instanceName`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#property-instances) useful.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) next time where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
